name: "terraform"
on:
  push:
    branches: ["main"]
    paths: ["terraform/**"]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform init
        working-directory: ./terraform
        run: terraform init
      - name: Terraform apply
        working-directory: ./terraform
        run: terraform apply --auto-approve
